import json
import logging
import os

import newrelic.agent
import requests

from main import BrandKitAutomater

# Set up logger
newrelic.agent.initialize()
logger = logging.getLogger(__name__)
logger.setLevel("INFO")

def create_content_kit(host: str, data: dict):
   url = f"{host}/content/content-kit/{data.get('brand_id')}"
   headers = {
        "Content-Type": "application/json",
         "x-lambda-token": os.environ.get('LAMBDA_CONTENT_KIT_AUTHOMATION_API_AUTH', '')
    }

   response = requests.post(url, json=data, headers=headers)
   logger.info(f"Status code for content kit creation api:{response.status_code}")

   if response.ok:
      response_api = response.json()
      logger.info(f"Getting response from conent kit creation api {response_api}")

      return response_api
   else:
      logger.info(f"Failed to update content kit. Status code: {response.status_code}")
      logger.info(f"Response: {response.text}")

      return None

def lambda_handler(event, context):

    function_name = os.environ.get("AWS_LAMBDA_FUNCTION_NAME", "unknown_lambda")
    application = newrelic.agent.application()
    with newrelic.agent.BackgroundTask(application=application, name=function_name, group="lambda"):
        API_HOST = os.environ.get("API_HOST",'https://staging.getgaana.com')

        if not API_HOST:
            raise ValueError("API_HOST environment variable not set")

        consumer = BrandKitAutomater()
        logger.info(f"{context = }")

        for record in event["Records"]:
            message = json.loads(record["body"])
            logger.info(f"{message = }")
            data = consumer.process_message(message)


            success = data.get('success')


            if success:
                output_format = data.get('output_format')
                logger.info(f"{output_format}")
                create_content_kit(f"{API_HOST}", output_format)

            else:
                queue_name = 'BrandKitAutomation Queue'
                logger.info(f"{data.get('error_message','Error Not generated by AI service')} | {queue_name}")
                logger.info(f"{record = } unable process successfully")

        return {"statusCode":200}
