import os
import json

import boto3

from main import VideoGenerator

def lambda_handler(event, context):

    client = boto3.client("secretsmanager")

    secret_value = client.get_secret_value(SecretId="google_service_account")
    creds = json.loads(secret_value["SecretString"]).get('google_service_account', '')

    cred_path = "/tmp/google_sa.json"
    with open(cred_path, "w") as f:
        f.write(creds)

    print(f"stored creds {cred_path = }")

    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = cred_path


    print("=== [lambda_handler] Starting ===")

    # Check environment variables
    required_env_vars = ["BUCKET", "PROMPT_OUTPUT_QUEUE_URL", "AZURE_OPENAI_KEY", "GEMINI_API_KEY"]
    missing_vars = [var for var in required_env_vars if not os.environ.get(var)]
    if missing_vars:
        raise ValueError(f"Missing environment variables: {missing_vars}")

    print(f"[DEBUG] Environment variables checked. All present.")

    # Log incoming event dumps put the logs in each line so avoid that
    # Process each SQS record
    for i, record in enumerate(event.get("Records", []), 1):
        print(f"\n=== [Record {i}] Processing === {record = }")
        consumer = VideoGenerator()

        try:
            message = json.loads(record["body"])
        except Exception as e:
            print(f"[ERROR] Failed to parse record body: {e}")
            print(f"[DEBUG] Raw body: {record.get('body')}")
            continue

        # Process the message
        try:
            data = consumer.process_message(message)
        except Exception as e:
            print(f"[ERROR] process_message failed: {e}")
            data = {"success": False, "error_message": str(e)}

        success = data.get('success', False)

        if success:
            output_format = data.get('output_format')

            try:
                consumer.send_to_output_queue(output_format)
            except Exception as e:
                print(f"[ERROR] Failed to send output to queue: {e}")
        else:
            queue_name = f'{consumer.__class__.__name__}'
            message["error_message"] = (
                f"{data.get('error_message','Error not generated by AI service')} | {queue_name}"
            )
            message["status"] = "failed"
            message["generate_config"] = message.get('id')
            try:
                consumer.send_to_output_queue(message=message)
                print(f"[DEBUG] Sent failure message to queue.")
            except Exception as e:
                print(f"[ERROR] Failed to send failure message to queue: {e}")

            print(f"[WARNING] Record {i} failed: {data.get('error_message','Unknown error')} | Queue: {queue_name}")
            print(f"[DEBUG] Record details: {json.dumps(record, indent=2)}")

    print("=== [lambda_handler] Completed ===")
    return {"statusCode": 200}
