import json
import logging
import os

import newrelic.agent

from main import TrendsProcessor

newrelic.agent.initialize()
logger = logging.getLogger(__name__)
logger.setLevel("INFO")

def lambda_handler(event, context):
    function_name = os.environ.get("AWS_LAMBDA_FUNCTION_NAME", "unknown_lambda")
    application = newrelic.agent.application()
    with newrelic.agent.BackgroundTask(application=application, name=function_name, group="lambda"):
        consumer = TrendsProcessor()
        logger.info(f"{context = }")

        for record in event["Records"]:
            message = json.loads(record["body"])
            logger.info(f"{message = }")
            data = consumer.process_message(message)

            success = data.get('success')

            if success:
                logger.info(f"{record = } processed and deleted successfully ")

            else:
                queue_name = 'Trends Queue'
                logger.info(f"{data.get('error_message','Error Not generated by AI service')} | {queue_name}")
                logger.info(f"{record = } unable process successfully")


            return {"statusCode":200}
