

import json
import logging
import os

from main import Consumer

logger = logging.getLogger(__name__)


def lambda_handler(event, context):
    if (
            not os.environ.get("BUCKET")
            or not os.environ.get("PROMPT_OUTPUT_QUEUE_URL")
            or not os.environ.get("AZURE_OPENAI_KEY")
            or not os.environ.get("GEMINI_API_KEY")
        ):
        raise ValueError(
            "BUCKET or "
            "PROMPT_OUTPUT_QUEUE_URL or "
            "AZURE_OPENAI_KEY or "
            "GEMINI_API_KEY"
            "environment variable not set"
        )



    print(f"{event = }")

    for record in event["Records"]:
        message = None
        data = {}
        consumer = Consumer(api_key=os.environ.get("GEMINI_API_KEY"))
        try:
            message = json.loads(record["body"])
        except Exception as e:
            data = {"error_message": f"Failed to parse record body. Error: {e}"}
            print(f"Failed to parse record body. Error: {e}")
            print(f"Raw body: {record['body']}")

        logger.info(f"{message = }")
        if message:
            data = consumer.process_message(message)
            success = data.get('success')
        else:
            success = False

        if success:
            output_format = data.get('output_format')
            logger.info(f"{output_format}")
            consumer.send_to_output_queue(output_format)

        else:
            queue_name = f'{consumer.__class__.__name__}'
            message["error_message"] = (
                    f"{data.get('error_message','Error Not generated by AI service')} | {queue_name}"
                )
            message["status"] = "failed"
            message["generate_config"] = message.get('id')
            consumer.send_to_output_queue(message=message)
            logger.info(f"{data.get('error_message','Error Not generated by Ideas-Alpha service')} | {queue_name}")
            logger.info(f"{record = } unable to process successfully")

    return {"statusCode":200}
